.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH envio 1  "envio " 
.SH NAME
envio
.SH SYNOPSIS
\fBenvio\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
envio\-profile(1)
.TP
envio\-set(1)
Set or update environment variables in a profile
.TP
envio\-unset(1)
Remove an environment variable from a profile
.TP
envio\-load(1)
Load all environment variables in a profile for use in your terminal sessions
.TP
envio\-unload(1)
Unload a profile
.TP
envio\-run(1)
Run a command with the environment variables from a profile
.TP
envio\-import(1)
Import a profile from a file, URL, or .env file
.TP
envio\-export(1)
Export a profile to a file
.TP
envio\-version(1)
Print the version
.TP
envio\-help(1)
Print this message or the help of the given subcommand(s)
