.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH envio 1  "envio " 
.SH NAME
envio
.SH SYNOPSIS
\fBenvio\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
envio\-create(1)
Create a new profile
.TP
envio\-add(1)
Add envionment variables to a profile
.TP
envio\-load(1)
Load all environment variables in a profile for use in your terminal sessions
.TP
envio\-unload(1)
Unload a profile
.TP
envio\-launch(1)
Launch a program with a profile
.TP
envio\-remove(1)
Remove a environment variable from a profile
.TP
envio\-list(1)
List all the environment variables in a profile or all the profiles currenty stored
.TP
envio\-update(1)
Update environment variables in a profile
.TP
envio\-export(1)
Export a profile to a file if no file is specified it will be exported to a file named .env
.TP
envio\-import(1)
Download a profile over the internet and import it into the system or import a locally stored profile into your current envio installation
.TP
envio\-version(1)
Print the version
.TP
envio\-help(1)
Print this message or the help of the given subcommand(s)
