.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH envio 1  "envio " 
.SH NAME
envio
.SH SYNOPSIS
\fBenvio\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
envio\-profile(1)
Manage profiles
.TP
envio\-set(1)
Set or update environment variables in a profile
.TP
envio\-unset(1)
Remove environment variables from a profile
.TP
envio\-load(1)
Load environment variables from a profile for use in the current terminal session
.TP
envio\-unload(1)
Unload a profile from the current terminal session
.TP
envio\-run(1)
Run a command with profile environment variables
.TP
envio\-import(1)
Import a profile from a file or url
.TP
envio\-export(1)
Export the environment variables of a profile to a file
.TP
envio\-tui(1)
launch the interactive TUI application
.TP
envio\-version(1)
Print version information
