complete -c envio -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c envio -n "__fish_use_subcommand" -f -a "profile" -d 'manage profiles'
complete -c envio -n "__fish_use_subcommand" -f -a "set" -d 'set or update environment variables in a profile'
complete -c envio -n "__fish_use_subcommand" -f -a "unset" -d 'remove environment variables from a profile'
complete -c envio -n "__fish_use_subcommand" -f -a "load" -d 'load environment variables from a profile for use in the current terminal session'
complete -c envio -n "__fish_use_subcommand" -f -a "unload" -d 'unload a profile from the current terminal session'
complete -c envio -n "__fish_use_subcommand" -f -a "run" -d 'run a command with profile environment variables'
complete -c envio -n "__fish_use_subcommand" -f -a "import" -d 'import a profile from a file, url, or .env file'
complete -c envio -n "__fish_use_subcommand" -f -a "export" -d 'export a profile to a file'
complete -c envio -n "__fish_use_subcommand" -f -a "version" -d 'print version information'
complete -c envio -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c envio -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from show" -f -a "create" -d 'create a new profile'
complete -c envio -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from show" -f -a "delete" -d 'delete a profile'
complete -c envio -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from show" -f -a "list" -d 'list all profiles'
complete -c envio -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from show" -f -a "show" -d 'show environment variables in a profile'
complete -c envio -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from create" -s f -l from-file -d 'file path to load environment variables from' -r
complete -c envio -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from create" -s e -l envs -d 'environment variables to add (format: KEY=VALUE or only provide KEY and the value will be prompted for)' -r
complete -c envio -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from create" -s k -l cipher-kind -d 'encryption cipher to use' -r
complete -c envio -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from create" -s c -l comments -d 'add comments to the provided environment variables'
complete -c envio -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from create" -s d -l expires -d 'add expiration dates to the provided environment variables'
complete -c envio -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c envio -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c envio -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from list" -l no-pretty-print -d 'disable pretty printing'
complete -c envio -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c envio -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from show" -s c -l show-comments -d 'display comments for environment variables'
complete -c envio -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from show" -s d -l show-expiration -d 'display expiration dates for environment variables'
complete -c envio -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from show" -l no-pretty-print -d 'disable pretty printing'
complete -c envio -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c envio -n "__fish_seen_subcommand_from set" -s c -l comments -d 'add comments to the provided environment variables'
complete -c envio -n "__fish_seen_subcommand_from set" -s d -l expires -d 'add expiration dates to the provided environment variables'
complete -c envio -n "__fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c envio -n "__fish_seen_subcommand_from unset" -s h -l help -d 'Print help'
complete -c envio -n "__fish_seen_subcommand_from load" -s h -l help -d 'Print help'
complete -c envio -n "__fish_seen_subcommand_from unload" -s h -l help -d 'Print help'
complete -c envio -n "__fish_seen_subcommand_from run" -s h -l help -d 'Print help'
complete -c envio -n "__fish_seen_subcommand_from import" -s n -l profile-name -d 'name for the imported profile' -r
complete -c envio -n "__fish_seen_subcommand_from import" -s h -l help -d 'Print help'
complete -c envio -n "__fish_seen_subcommand_from export" -s t -l to -d 'output file path' -r
complete -c envio -n "__fish_seen_subcommand_from export" -s k -l keys -d 'comma-separated list of keys to export leave empty to prompt for selection' -r
complete -c envio -n "__fish_seen_subcommand_from export" -s h -l help -d 'Print help'
complete -c envio -n "__fish_seen_subcommand_from version" -s v -l verbose -d 'show verbose version information'
complete -c envio -n "__fish_seen_subcommand_from version" -s h -l help -d 'Print help'
